name: osca_dart
description: API for Osca
version: 0.0.1
author: Jonas Uekötter

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  http: ">=0.12.0 <1.0.0"
  xml: ">=3.3.0 <4.0.0"
  crypto: ">=2.0.6 <3.0.0"
  pointycastle: <=1.0.2
  cryptography: 1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ">=1.9.0 <2.0.0"
