name: osca_dart
description: API for Osca
version: 0.0.1
author: Jonas Uekötter

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  http: ^0.12.0
  xml: ^4.0.0
  crypto: ">=2.0.6 <3.0.0"
  pointycastle: ^2.0.0
  cryptography: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ">=1.9.0 <2.0.0"
