name: osca_dart
description: API for Osca
version: 0.0.1
author: Jonas Uekötter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ">=0.12.0 <1.0.0"
  xml: ">=3.3.0 <4.0.0"
  crypto: ">=2.0.6 <3.0.0"

dev_dependencies:
  test: ">=1.6.0 <2.0.0"
  pedantic: ">=1.9.0 <2.0.0"
